CocoaPods/pod-template

- NAME.podspec
More info here https://github.com/CocoaPods/CocoaPods/issues/3087
> Podspec source_files should be recursive by default

- NAME.podspec
Updated per review
https://github.com/bunchjesse/pod-template/commit/4ecd24de1de2d32ef503d419cd452dba91bfb9db
https://github.com/CocoaPods/CocoaPods/issues/3087#issuecomment-72394849
> Don't specify extensions in source_files

- POD_README.md
> [POD_README] Link to pod pages instead of cocoadocs

- setup/ProjectManipulator.rb
https://github.com/CocoaPods/pod-template/issues/108
> Fix removal of demo project

- templates/ios/Example/PROJECT.xcodeproj/project.pbxproj
- templates/ios/Example/PROJECT.xcodeproj/xcshareddata/xcschemes/PROJECT.xcscheme
- templates/swift/Example/PROJECT.xcodeproj/project.pbxproj
- templates/swift/Example/PROJECT.xcodeproj/xcshareddata/xcschemes/PROJECT.xcscheme
I' encountered the same problem actually on the pod lib create command
> Try to fix build creation issue #111

- setup/ProjectManipulator.rb
- setup/TemplateConfigurator.rb
- templates/ios/Example/PROJECT/CPDAppDelegate.h
- templates/ios/Example/PROJECT/CPDAppDelegate.m
- templates/ios/Example/PROJECT/CPDViewController.h
- templates/ios/Example/PROJECT/CPDViewController.m
- templates/ios/Example/PROJECT/main.m
- templates/ios/Example/Tests/Tests.m
2014 hard code should be replaced by TODAYS_YEAR, and year is now @configurator.date.
> fix hard code of year 2014 in OC Example

- NAME.podspec
Corresponds with https://github.com/CocoaPods/CocoaPods/pull/3984
> Update the podspecs copy to match cocoapods' new defaults

- templates/ios/Example/PROJECT.xcodeproj/project.pbxproj
- templates/ios/Example/PROJECT.xcodeproj/xcshareddata/xcschemes/PROJECT.xcscheme
- templates/ios/Example/PROJECT/PROJECT-Info.plist
- templates/ios/Example/Tests/Tests-Info.plist
- templates/swift/Example/PROJECT.xcodeproj/project.pbxproj
- templates/swift/Example/PROJECT.xcodeproj/xcshareddata/xcschemes/PROJECT.xcscheme
- templates/swift/Example/PROJECT/Info.plist
- templates/swift/Example/Tests/Info.plist
> use recommended project settings fixes #142

- templates/swift/Example/PROJECT.xcodeproj/project.pbxproj
Issue introduced in Xcode 7.3.
> remove TEST_HOST for Swift libs to fix #149

- README.md
removed periods from bullet list of main features
> Use consistent punctuation for main features

- NAME.podspec
> in Ruby, preferring single quotes to double quotes

- .travis.yml
Use the latest Xcode image and iPhone simulator available from Travis CI to ensure an out-of-the-box working `.travis.yml` file.
> working travis-ci example

- setup/ProjectManipulator.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/5758
> [ProjectManipulator] Add support for templates with aggregate targets

- setup/ConfigureSwift.rb
- setup/test_examples/quick.swift
Some changes to work in Swift 3
> Update to work in Swift 3

- templates/swift/Example/PROJECT.xcodeproj/project.pbxproj
- templates/swift/Example/PROJECT.xcodeproj/xcshareddata/xcschemes/PROJECT.xcscheme
- templates/swift/Example/PROJECT/AppDelegate.swift
Update template for examples to Swift 3.
> update swift template to swift 3

- templates/swift/Example/PROJECT.xcodeproj/project.pbxproj
closes https://github.com/CocoaPods/CocoaPods/issues/7894
> Fix app host reference for Swift template

- setup/MessageBank.rb
Update camelcase naming of `HasRunBefore` from `HasRunbefore`
> Update naming to HasRunBefore

- templates/ios/Example/PROJECT.xcodeproj/project.pbxproj
- templates/swift/Example/PROJECT.xcodeproj/project.pbxproj
Fixes CocoaPods/CocoaPods#8938
> Fix Xcode warning "directory not found for option -F"

- setup/ConfigureSwift.rb
Supersedes https://github.com/CocoaPods/pod-template/pull/231
closes https://github.com/CocoaPods/pod-template/issues/238
> Update Nimble pod dependency requirement

- setup/ConfigureiOS.rb
> ObjC class prefix should be upcase

- setup/ConfigureMacOSSwift.rb
- setup/ConfigureSwift.rb
Updating Quick test framework versions as they are very out-of-date. 😰
> ⬆️ Update Quick & Nimble

- setup/ConfigureMacOSSwift.rb
- setup/ConfigureSwift.rb
Updating both Nimble & Nimble-Snapshots to the latest versions
> Bumping Nimble versions
