CocoaPods/pod-template

- setup/test_examples/specta.m
Removed extraneous `});` from the Specta test template
> Fix syntax of Specta test example template

- setup/ConfigureiOS.rb
- setup/test_examples/xctest.m
Fixed `Test.m` template not being set up when selecting test framework: *None*.
Now assumes `XCTest` and applies a template to the test prefix header and `Test.m` example.
I don't see anything about the default 'test framework' when choosing *None* in the CocoaPods.org guide. `XCTest` makes sense as a default, so no changes required to the guide.
> Fixed Test.m template not being set up with *None* test framework.

- setup/TemplateConfigurator.rb
Currently, this will be the state of the project after setting it up
```bash
$ git status
On branch master
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   Example/yolo.xcodeproj/project.pbxproj
Untracked files:
(use "git add <file>..." to include in what will be committed)
Example/Podfile.lock
Example/Pods/
Example/yolo.xcworkspace/
no changes added to commit (use "git add" and/or "git commit -a")
```
While it makes sense to not check-in the files generated by CP, because of user-choice and education reasons, I don't think it is useful that the example project itself ends up in an unclean state. This is only a recipe for confusion and not committing it to source …
> Re-add the example project after `pod install`.

- .gitignore
- setup/TemplateConfigurator.rb
This allows pod-template projects to be buildable with Carthage by default. Prerequisite from the user side will be checking in their `Example/Pods` directory, as well as the generated workspace.
:warning: This depends on some changes to both CocoaPods and Carthage, before it is useful:
If the user adds dependencies, he will have to add a `Cartfile` to also make them known to Carthage.
Fixes #104
> Carthage support

- templates/ios/Example/PROJECT/PROJECT-Info.plist
Updates `PROJECT-Info.plist` to reflect changes made in #116 where the main storyboard was changed for Objective-C projects.
> Fix crash due to missing storyboard file

- setup/test_examples/quick.swift
The Quick test example had a small typo, so I fixed that.
Also, when I ran my tests in Xcode 7 Beta 2, the passing tests failed to run at all. I saw other examples that put the `context` within the `describe`, so did that here as well.
This did uncover a bug (probably in Quick itself?), namely that the test `will eventually pass` does not appear to be run at all.
> Fixed typo and run passing examples.

- .travis.yml
xcpretty 0.2.0 and newer defaults to use colour when the terminal is ANSI capable so the `-c` flag is no longer required.
> Remove -c option from xcpretty in Travis CI

- .travis.yml
This means that your pod will by built for all platforms by CocoaPods and fully lint your podspec so you don't come into surprises when you try to release for real and it doesn't work.
> Don't use the `--quick` option for pod lib lint in Travis CI

- setup/ConfigureSwift.rb
I try this command.
`pod lib create TestProject` and Select `Swift` , `Quick` 
Using Xcode 7.1 with Quick 0.3.1 leads errors and build does not success.
Quick version should be 0.8.0 written in documentation of Quick.
Do we have some reason using 0.3.1 which I have not taken care of ?
> Update Quick version

- NAME.podspec
- setup/MessageBank.rb
- setup/TemplateConfigurator.rb
- templates/swift/Example/Podfile
In the current version, your files would go into `Pod/Classes/Here.swift` but I think overall, it's less confusing to have them go into `[LibName]/Classes/Here.swift`.
Other than that, done some minor cleanup.
> Move the files for the pod into a folder with the same name as the project

- setup/ProjectManipulator.rb
- templates/ios/Example/Podfile
After I removed the line: 
```
source 'https://github.com/CocoaPods/Specs.git'
```
it threw the offsets for the App target to be removed from the podfile:
```
use_frameworks!
target '${POD_NAME}_Example', :exclusive => true do
pod '${POD_NAME}', :path => '../'
end
target '${POD_NAME}_Tests', :exclusive => true do
pod '${POD_NAME}', :path => '../'
${INCLUDED_PODS}
end
```
Where it used to delete 3 LOC from the 3rd line, it now needed to be 2 LOC. So this fixes that, and makes sure the obj-c Podfile has the same offsets.
> Fix Podfile generated when a project has no example app

- setup/ProjectManipulator.rb
previously it was doing a lot of specific line removals, which got more and more complex. Now instead it just outright replaces the podfile with a simpler, working one. This means indentation is correct, and devs need to know a lot less about the internals to understand what's going on.
> Simplify example-less projects

- setup/TemplateConfigurator.rb
Setup using `pod lib create` was failing due to a mismatch in case-sensitivity of the Pod directory.
> Fix to prevent failure in case-sensitive filesystems during setup.

- NAME.podspec
- setup/TemplateConfigurator.rb
Addresses https://github.com/CocoaPods/pod-template/issues/126
Command from: http://stackoverflow.com/a/13761822/1904232
Will fallback to current behaviour if github username is not found (git username). This is still valuable to keep around as user could be setting a private pod repository in another git hosting solution.)
> Grab github username if possible when expanding templates

- templates/swift/Example/PROJECT/AppDelegate.swift
Updated to use Swift 3 naming conventions. Latest version of Xcode(8.2.1) makes these same changes. Latest Xcode beta(8.3) is supporting swift 3 only, so it seems appropriate to make these changes
> Update AppDelegate.swift for swift 3

- setup/TemplateConfigurator.rb
This PR fixes the issues discussed in the issue https://github.com/CocoaPods/CocoaPods/issues/6652.
Basically, when you run pod lib create on a machine that had only the newer version of Cocoapods, it was failing with error “require': cannot load such file -- colored (LoadError)”. This is because Cocoapods does not ship with colored anymore, it only has colored2. This fix will make sure that the pod template uses the newer version and won’t fail anymore. 
@orta - As you suggested, I am creating this PR to merge this fix into master. Let me know if you need more info.
> Update the library colored to colored2 to fix the load error in create command

- setup/MessageBank.rb
- setup/TemplateConfigurator.rb
This PR fixes the issues discussed in the issue https://github.com/CocoaPods/CocoaPods/issues/6652
Basically, when you run pod lib create on a machine that had only the newer version of Cocoapods, it still fails despite the fixed in https://github.com/CocoaPods/pod-template/pull/207 because the syntax for underline change to underlined in colored2
@orta Let me know if you need more info.
> update syntax for colored2 to fix the load error in pod lib create command

- templates/ios/Example/PROJECT/Base.lproj/LaunchScreen.storyboard
- templates/ios/Example/PROJECT/Base.lproj/Main.storyboard
- templates/ios/Example/PROJECT/Images.xcassets/AppIcon.appiconset/Contents.json
- templates/swift/Example/PROJECT/Base.lproj/LaunchScreen.xib
- templates/swift/Example/PROJECT/Base.lproj/Main.storyboard
- templates/swift/Example/PROJECT/Images.xcassets/AppIcon.appiconset/Contents.json
1 -  Added default appicon data of "idiom" : "ios-marketing".
2 - Fixed storyboard warning of device selection of iPhone 8. (Because I need to do that every time when pod lib create MyLib)
Warning details:
"Choose an initial device view
The design canvas shows your interfaces as they will appear
on devices. Select a device to view your
interface by — this setting will be used for the initial view of your
interfaces, and can be changed to another device at any time."
> Updated swift and ios PROJECTs.

- setup/TemplateConfigurator.rb
Before:
```
target 'Merniva_Tests' do
inherit! :search_paths
pod 'Quick', '~> 1.2.0'
pod 'Nimble', '~> 7.0.2'
pod 'FBSnapshotTestCase' , '~> 2.1.4'
pod 'Nimble-Snapshots' , '~> 6.3.0'
end
```
After:
```
target 'Merniva_Tests' do
inherit! :search_paths
pod 'Quick', '~> 1.2.0'
pod 'Nimble', '~> 7.0.2'
pod 'FBSnapshotTestCase' , '~> 2.1.4'
pod 'Nimble-Snapshots' , '~> 6.3.0'
end
```
> Fix indent on included pods on Podfile template

- .gitignore
The problem https://github.com/Quick/Nimble/issues/490 happens even on `CocoaPods/pod-template`.
This PR will fix it.
P.S. 
I bring the code from github/gitignore:
https://github.com/github/gitignore/blob/ebb436c5590ced8ae58eea87e6400abc759f60d7/Objective-C.gitignore#L39-L44
> fix: .gitignore removes Carthage files of dependencies (Nimble).

- templates/ios/Example/Podfile
If not present, a warning is shown on every `pod install`.
```
[!] Automatically assigning platform `ios` with version `10.0` on target `POD_NAME` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```
Reference: https://guides.cocoapods.org/syntax/podfile.html#platform
> Add platform specification

- templates/ios/Example/PROJECT.xcodeproj/project.pbxproj
closes https://github.com/CocoaPods/CocoaPods/issues/8932
If a user creates an ObjC project then [this](https://github.com/CocoaPods/pod-template/tree/master/templates/ios/Example) template is used. However, adding a test framework which uses Swift would cause pod template creation to fail because `SWIFT_VERSION` is not set on the ObjC template anywhere. This PR adds `SWIFT_VERSION` into the `PROJECT.xcodeproj` which can be used to derive the Swift version.
All other templates used Swift 4.0 so I used that as well.
> Set SWIFT_VERSION setting for ObjC template project

- NAME.podspec
Resolves #250 - default pods from `pod create init` will no longer cause a warning on XCode 12.
> Raise default iOS `deployment_target` to 9.0

- setup/ConfigureSwift.rb
- templates/ios/Example/Podfile
- templates/swift/Example/Podfile
iOS version number is not equal between Podfile and Podspec
This will cause an error like this:
```
[!] CocoaPods could not find compatible versions for pod "Test":
In Podfile:
Test (from `../`)
Specs satisfying the `Test (from `../`)` dependency were found, but they required a higher minimum deployment target.
```
> Fix iOS version number not equal between Podfile and Podspec

- .gitignore
On June 13, 2016, at WWDC16, OS X was renamed macOS.
But here in the gitignore file this hasn't changed.
Please merge it.
> OS X -> macOS in gitignore

- .gitignore
As pointed out in the issue #205, profile is a common folder name and with this line in the .gitignore anything inside a profile folder (not case sensitive) would be ignored. 
@orta mentioned that this line was also removed from https://github.com/github/gitignore/blob/main/Objective-C.gitignore
---
By curiosity, what was the original intention to use this profile line? Just to make sure this PR is not going against any pre-existing definition.
> Update .gitignore - removing profile

- setup/ProjectManipulator.rb
- setup/TemplateConfigurator.rb
Because  deprecated methods `Dir.exists?`, `File.exists?` were removed from Ruby 3, you will get the following error when running `pod lib create <YourPodNname>` with Ruby 3:
```
/private/var/folders/mb/_fcb_z0j6knf8tphxd0fmmmm0000gp/T/play_cocoapods/MyPod/setup/ProjectManipulator.rb:128:in `block in replace_internal_project_settings': undefined method `exists?' for Dir:Class (NoMethodError)
next if Dir.exists? name
^^^^^^^^
Did you mean?  exist?
from /private/var/folders/mb/_fcb_z0j6knf8tphxd0fmmmm0000gp/T/play_cocoapods/MyPod/setup/ProjectManipulator.rb:127:in `each'
from /private/var/folders/mb/_fcb_z0j6knf8tphxd0fmmmm0000gp/T/play_cocoapods/MyPod/setup/ProjectManipulator.rb:127:in `replace_internal_project_settings'
from /private/var/folders/mb/_fcb_z0j6knf8tphxd0fmmmm0000gp/T/play_coc …
```
> Fix "pod lib create" error when running with Ruby 3
